ball:
  radius: 5.0
  color: !Hsla {
    hue: 179,
    saturation: 0.82,
    lightness: 0.56,
    alpha: 1.0,
  }
  initial_speed: 200.0
  speed_increase: 1.0
  offset_from_paddle: 40.0
paddle:
  width: 150.0
  height: 15.0
  offset_from_bottom: 20.0
  color: !Rgba {
    red: 1.0,
    green: 1.0,
    blue: 1.0,
    alpha: 1.0,
  }
  initial_speed: 200.0
block:
  rows: 10
  columns: 15
  width: 60.0
  height: 15.0
  horizontal_offset: 10.0
  vertical_offset: 5.0
  offset_from_top: 120.0
stats:
  lifes: 3